name: Unit Tests

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  uvu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install
          npm test
